config/routes.rb
Rails.application.routes.draw do
  resources :schools do
    member do
      get :delete
    end
  end
  resources :departments do
    member do
      get :delete
    end
  end
  resources :courses do
    member do
      get :delete
    end
  end
  resources :teachers do
    member do
      get :delete
    end
  end
  resources :students do
    member do
      get :delete
    end
  end
  resources :semesters do
    member do
      get :delete
    end
  end
  resources :course_enrollments
end

app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :course
  belongs_to :student
  scope :sorted, lambda { order('course_id ASC') }
end

app/controllers/course_enrollments_controller.rb
class CourseEnrollmentsController < ApplicationController
  before_action :find_student
  before_action :find_course
  before_action :find_course_enroll, only: %i[show edit delete]
  def index
    @course_enrollments = @course.course_enrollments.sorted
  end

  def show; end

  private
  def find_course_enroll
    @course_enrollment = CourseEnrollment.find(params[:id])
  end
  def find_student
    if params[:student_id]
    @student = Student.find(params[:student_id])
    end
  end
  def find_course
    if params[:course_id]
    @course = Course.find(params[:course_id])
    end
  end
end

app/helpers/course_enrollments_helper.rb
module CourseEnrollmentsHelper
end

app/views/course_enrollments/index.html.erb
<div class="course_enrollment index">
  <%= link_to t('shared.all.crs_back'), courses_path(department_id: @course.department_id) %>
  <div id= "showname">
    <p class="center"><%= @course.course_name %></p>
  </div>
  <%= image_tag('plus.png', size: '12x12', alt: '+') %>
  <%= link_to t('students.all.std_add'), new_student_path(course_id: @course.id )%>
  <br /><br />
  <table class="listing" summary="Course List">
    <tr>
      <th><%= t('students.all.std_number') %></th>
      <th><%= t('students.all.std_name') %></th>
      <th><%= t('shared.all.prog') %></th>
      <th><%= t('shared.all.actions') %></th>
    </tr>
    <% @course_enrollments.each do |course_enrollment| %>
        <tr>
          <td><%= course_enrollment.student.std_number %>
          <td><%= course_enrollment.student.std_name %>
          <td><%= course_enrollment.student.std_program %>
          </td>
          <td class="actions">
            <%= link_to t('shared.all.show'), course_enrollment_path(course_enrollment, course_id: @course.id) %>
            <%= link_to t('shared.all.delete'), delete_student_path(course_enrollment.student, course_id: @course.id) %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/course_enrollments/show.html.erb
<%= link_to t('shared.all.crs_enroll_back'), course_enrollments_path(course_id: @course.id) %>
<div id= "showname">
  <p class="center"><%= @course.course_name %></p>
</div>
<div class="students show">
  <h2><%= t('students.all.std_details') %></h2>
  <table summary="Student detail view">
    <tr>
      <th><%= t('students.all.std_number') %></th>
      <td><%= @course_enrollment.student.std_number %></td>
    </tr>
    <tr>
      <th><%= t('students.all.std_name') %></th>
      <td><%= @course_enrollment.student.std_name %></td>
    </tr>
    <tr>
      <th><%= t('students.all.std_email') %></th>
      <td><%= @course_enrollment.student.std_email %></td>
    </tr>
    <tr>
      <th><%= t('students.all.std_contact') %></th>
      <td><%= @course_enrollment.student.std_contact %></td>
    </tr>
    <tr>
      <th><%= t('students.all.std_address') %></th>
      <td><%= @course_enrollment.student.std_address %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.prog') %></th>
      <td><%= @course_enrollment.student.std_program %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.dept') %></th>
      <td><%= @course_enrollment.student.std_dept_name %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.sem') %></th>
      <td><%= @course_enrollment.student.std_semester %></td>
    </tr>
  </table>
</div>