config/routes.rb
Rails.application.routes.draw do
  resources :schools do
    member do
      get :delete
    end
  end
  resources :departments do
    member do
      get :delete
    end
  end
  resources :courses do
    member do
      get :delete
    end
  end
  resources :teachers do
    member do
      get :delete
    end
  end
  resources :students do
    member do
      get :delete
    end
  end
  resources :semesters do
    member do
      get :delete
    end
  end
  resources :course_enrollments
end

app/models/department.rb
class Department < ApplicationRecord
  CAPACITY = *(50..550)
  belongs_to :school
  has_many :courses
  has_many :teachers
  scope :sorted, lambda { order('position ASC') }
  validates :school_id, presence: true
  validates :name, presence: true, uniqueness: true
  validates :position, presence:  true, length: { minimum: 1 }, numericality: true
  validates :head_name, presence: true, uniqueness: true
  validates :capacity,
            presence: true,
            numericality: true,
            inclusion: { in: 50..550, message: I18n.t('departments.all.dept_capacity_message')}
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :find_school_id
  before_action :find_department, only: %i[show edit update delete destroy]
  def index
    @departments = @school.departments.sorted
  end

  def show; end

  def new
    @department = Department.new( school_id: @school.id )
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:notice] = t('departments.all.dept_notice_create')
      redirect_to(departments_path( school_id: @school.id ))
    else
      render :new
    end
  end

  def edit; end

  def update
    if @department.update_attributes(department_params)
      flash[:notice] = t('departments.all.dept_notice_edit')
      redirect_to(departments_path( @department, school_id: @school.id ))
    else
      render :edit
    end
  end

  def delete; end

  def destroy
    @department.destroy
    flash[:notice] = t('departments.all.dept_notice_delete')
    redirect_to(departments_path( school_id: @school.id ))
  end

  private
  def department_params
    params.require(:department).permit(:name, :position, :head_name, :description, :capacity, :school_id)
  end
  def find_department
    @department = Department.find(params[:id])
  end
  def find_school_id
    if params[:school_id]
    @school = School.find(params[:school_id])
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/delete.html.erb
<%= link_to t('shared.all.dept_back'), departments_path( school_id: @school.id ) %>
<div class ="department delete">
  <h2><%= t('departments.all.dept_delete') %></h2>
  <%= simple_form_for(@department, url: department_path(@department,school_id: @school.id), method: 'delete') do |f| %>
      <p class="center"><%= t('departments.all.dept_delete_message') %></p>
      <p class="reference-name, center" ><%= f.object.name %></p>
      <%= f.submit t('departments.all.dept_delete') %>
  <% end %>
</div>

app/views/departments/edit.html.erb
<%= link_to t('shared.all.dept_back'), departments_path( school_id: @school.id ) %>
<div class ="department edit">
  <h2><%= t('departments.all.dept_update') %></h2>
  <%= simple_form_for @department, url: department_path(@department,school_id: @school.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :school_id, school_id: @school.id  %>
      <%= f.input :name %>
      <%= f.input :position %>
      <%= f.input :head_name %>
      <%= f.input :description %>
      <%= f.input :capacity %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/departments/index.html.erb
<div class="department index">
  <%= link_to t('shared.all.sch_back'), schools_path %>
  <div id= "showname">
    <p class="center"><% @school.name %></p>
  </div>
  </table>
  <h2><%=t('departments.all.dept')%></h2>
  <%= image_tag('plus.png', size: '12x12', alt: '+') %>
  <%= link_to t('departments.all.dept_add'), new_department_path(school_id: @school.id) %>
  <br /><br />
  <table class="listing" summary="Department List">
    <tr class="header">
      <th><%=t('shared.all.serial')%></th>
      <th class="center"><%=t('departments.all.dept_name')%></th>
      <th class="center"><%=t('departments.all.dept_description')%></th>
      <th class="center"><%=t('departments.all.dept_head_name')%></th>
      <th class="center"><%=t('departments.all.dept_capacity')%></th>
      <th class="center"><%=t('shared.all.actions')%></th>
    </tr>
    <% @departments.each do |department| %>
        <tr>
          <td><%= department.position %></td>
          <td><%= department.name %></td>
          <td><%= department.description %></td>
          <td><%= department.head_name %></td>
          <td><%= department.capacity %></td>
          <td class="actions">
            <%= link_to t('departments.all.dept_crs'), courses_path(department_id: department.id) %>
            <%= link_to t('departments.all.dept_teacher'), teachers_path(department_id: department.id) %>
            <%= link_to t('shared.all.show'), department_path(department, school_id: @school.id) %>
            <%= link_to t('shared.all.edit'), edit_department_path(department, school_id: @school.id) %>
            <%= link_to t('shared.all.delete'), delete_department_path(department, school_id: @school.id) %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/departments/new.html.erb
<%= link_to t('shared.all.dept_back'), departments_path( school_id: @school.id ) %>
<div class ="departments new">
  <h2><%= t('departments.all.dept_new') %></h2>
  <%= simple_form_for @department, url: departments_path(school_id: @school.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :school_id, school_id: @school.id  %>
      <%= f.input :name %>
      <%= f.input :position %>
      <%= f.input :head_name %>
      <%= f.input :description %>
      <%= f.input :capacity %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/departments/show.html.erb
<%= link_to t('shared.all.dept_back'), departments_path( school_id: @school.id ) %>
<div class="departments show">
  <h2><%= t('departments.all.dept_details') %></h2>
  <table summary="Department detail view">
    <tr>
      <th><%= t('departments.all.dept_name')%></th>
      <td><%= @department.name %></td>
    </tr>
    <tr>
      <th><%= t('departments.all.dept_description')%></th>
      <td><%= @department.description %></td>
    </tr>
    <tr>
      <th><%= t('departments.all.dept_head_name')%></th>
      <td><%= @department.head_name %></td>
    </tr>
    <tr>
      <th><%= t('departments.all.dept_capacity')%></th>
      <td><%= @department.capacity %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.createdat')%></th>
      <td><%= @department.created_at %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.updatedat')%></th>
      <td><%= @department.updated_at %></td>
    </tr>
  </table>
</div>