config/routes.rb
Rails.application.routes.draw do
  resources :schools do
    member do
      get :delete
    end
  end
  resources :departments do
    member do
      get :delete
    end
  end
  resources :courses do
    member do
      get :delete
    end
  end
  resources :teachers do
    member do
      get :delete
    end
  end
  resources :students do
    member do
      get :delete
    end
  end
  resources :semesters do
    member do
      get :delete
    end
  end
  resources :course_enrollments
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  scope :sorted, lambda {order('teacher_id ASC')}
  validates :teacher_id, presence: true, uniqueness: true, numericality: true, length: { minimum: 2, maximum: 5 }
  validates :teacher_name, presence: true
  validates :Email, presence: true, uniqueness: true
  validates :Designation, presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_department_id
  before_action :find_teacher, only: %i[show edit update delete destroy]
  def index
    @teachers = @department.teachers.sorted
  end

  def show ; end

  def new
    @teacher = Teacher.new(department_id: @department.id)
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash[:notice] = t('teachers.all.tch_notice_create')
      redirect_to(teachers_path( department_id: @department.id ))
    else
      render :new
    end
  end

  def edit ; end

  def update
    if @teacher.update_attributes(teacher_params)
      flash[:notice] = t('teachers.all.tch_notice_edit')
      redirect_to(teachers_path(@teacher, department_id: @department.id ))
    else
      render :edit
    end
  end

  def delete ; end

  def destroy
    @teacher.destroy
    flash[:notice] = t('teachers.all.tch_notice_delete')
    redirect_to(teachers_path(department_id: @department.id))
  end

  private
  def teacher_params
    params.require(:teacher).permit(:teacher_id, :teacher_name, :Contact, :Email, :Designation, :department_id)
  end
  def find_teacher
    @teacher = Teacher.find(params[:id])
  end
  def set_department_id
    if params[:department_id]
      @department = Department.find(params[:department_id])
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/delete.html.erb
<%= link_to t('shared.all.tch_back'), teachers_path(department_id: @department.id) %>
<div class ="faculty delete">
  <h2><%= t('teachers.all.tch_delete') %></h2>
  <%= simple_form_for(@teacher, url: teacher_path(@teacher, department_id: @department.id), method: 'delete') do |f| %>
      <p class="center"><%= t('teachers.all.tch_delete_message') %></p>
      <p class="reference-name, center" ><%= f.object.teacher_name %></p>
      <%= f.submit t('teachers.all.tch_delete') %>
  <% end %>
</div>

app/views/teachers/edit.html.erb
<%= link_to t('shared.all.tch_back'), teachers_path(department_id: @department.id) %>
<div class ="teachers new">
  <h2><%= t('teachers.all.tch_update') %></h2>
  <%= simple_form_for @teacher, url: teacher_path(@teacher, department_id: @department.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :department_id, department_id: @department.id  %>
      <%= f.input :teacher_id, label: t('teachers.all.tch_ID') %>
      <%= f.input :teacher_name, label: t('teachers.all.tch_name') %>
      <%= f.input :Email, placeholder: 'userdomain.com' %>
      <%= f.input :Contact, label: t('teachers.all.tch_contact') %>
      <%= f.input :Designation, collection: [ "Associate Professor", "Professor", "Lecturer", "Junior Lecturer" ] %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/teachers/index.html.erb
<div class="teacher index">
  <%= link_to t('shared.all.dept_back'), departments_path(school_id: @department.school_id) %>
  <div id= "showname">
    <p class="center"><%= t('departments.all.dept_of')%><%= @department.name %></p>
  </div>
  </table>
  <h2><%=t('teachers.all.tch')%></h2>
  <%= image_tag('plus.png', size: '12x12', alt: '+') %>
  <%= link_to t('teachers.all.tch_add'), new_teacher_path(department_id: @department.id) %>
  <br /><br />
  <table class="listing" summary="Teacher List">
    <tr class="header">
      <th class="center"><%=t('teachers.all.tch_ID')%></th>
      <th class="center"><%=t('teachers.all.tch_name')%></th>
      <th class="center"><%=t('teachers.all.tch_email')%></th>
      <th class="center"><%=t('teachers.all.tch_contact')%></th>
      <th class="center"><%=t('teachers.all.tch_desig')%></th>
      <th class="center"><%=t('shared.all.actions')%></th>
    </tr>
    <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.teacher_id %></td>
          <td><%= teacher.teacher_name %></td>
          <td><%= teacher.Email %></td>
          <td><%= teacher.Contact %></td>
          <td><%= teacher.Designation %></td>
          <td class="actions">
            <%= link_to t('shared.all.show'), teacher_path(teacher, department_id: @department.id) %>
            <%= link_to t('shared.all.edit'), edit_teacher_path(teacher, department_id: @department.id) %>
            <%= link_to t('shared.all.delete'), delete_teacher_path(teacher, department_id: @department.id) %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/teachers/new.html.erb
<%= link_to t('shared.all.tch_back'), teachers_path(department_id: @department.id) %>
<div class ="teachers new">
  <h2><%= t('teachers.all.tch_new') %></h2>
  <%= simple_form_for @teacher, url: teachers_path(department_id: @department.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :department_id, department_id: @department.id  %>
      <%= f.input :teacher_id, label: t('teachers.all.tch_ID') %>
      <%= f.input :teacher_name, label: t('teachers.all.tch_name') %>
      <%= f.input :Email, placeholder: 'userdomain.com' %>
      <%= f.input :Contact, label: t('teachers.all.tch_contact') %>
      <%= f.input :Designation, collection: [ "Associate Professor", "Professor", "Lecturer", "Junior Lecturer" ] %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/teachers/show.html.erb
<%= link_to t('shared.all.tch_back'), teachers_path(department_id: @department.id) %>
<div class="schools show">
  <h2><%= t('teachers.all.tch_details') %></h2>
  <table summary="Faculty detail view">
    <tr>
      <th><%= t('teachers.all.tch_ID') %></th>
      <td><%= @teacher.teacher_id %></td>
    </tr>
    <tr>
      <th><%= t('teachers.all.tch_name') %></th>
      <td><%= @teacher.teacher_name %></td>
    </tr>
    <tr>
      <th><%= t('teachers.all.tch_email') %></th>
      <td><%= @teacher.Email %></td>
    </tr>
    <tr>
      <th><%= t('teachers.all.tch_contact') %></th>
      <td><%= @teacher.Contact %></td>
    </tr>
    <tr>
      <th><%= t('teachers.all.tch_desig') %></th>
      <td><%= @teacher.Designation %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.createdat') %></th>
      <td><%= @teacher.created_at %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.updatedat') %></th>
      <td><%= @teacher.updated_at %></td>
    </tr>
  </table>
</div>