config/routes.rb
Rails.application.routes.draw do
  resources :schools do
    member do
      get :delete
    end
  end
  resources :departments do
    member do
      get :delete
    end
  end
  resources :courses do
    member do
      get :delete
    end
  end
  resources :teachers do
    member do
      get :delete
    end
  end
  resources :students do
    member do
      get :delete
    end
  end
  resources :semesters do
    member do
      get :delete
    end
  end
  resources :course_enrollments
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_department_id
  before_action :find_course, only: %i[show edit update delete destroy]
  def index
    @courses = @department.courses.sorted
  end

  def show; end

  def new
    @course = Course.new(department_id: @department.id)
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = t('courses.all.crs_notice_create')
      redirect_to(courses_path( department_id: @department.id ))
    else
      render :new
    end
  end

  def edit; end

  def update
    if @course.update_attributes(course_params)
      flash[:notice] = t('courses.all.crs_notice_edit')
      redirect_to(courses_path(@course, department_id: @department.id ))
    else
      render :edit
    end
  end

  def delete; end

  def destroy
    @course.destroy
    flash[:notice] = t('courses.all.crs_notice_delete')
    redirect_to(courses_path(department_id: @department.id))
  end

  private
  def course_params
    params.require(:course).permit(:course_ID,
                                   :course_name,
                                   :position,
                                   :credits,
                                   :department_id)
  end
  def find_course
    @course = Course.find(params[:id])
  end
  def set_department_id
    if params[:department_id]
      @department = Department.find(params[:department_id])
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/delete.html.erb
<%= link_to t('shared.all.crs_back'), courses_path(department_id: @department.id) %>
<div class ="courses delete">
  <h2><%= t('courses.all.crs_delete') %></h2>
  <%= simple_form_for(@course, url: course_path(@course, department_id: @department.id), method: 'delete') do |f| %>
      <p class="center"><%= t('courses.all.crs_delete_message') %></p>
      <p class="reference-name, center" ><%= f.object.course_name %></p>
      <%= f.submit t('courses.all.crs_delete') %>
  <% end %>
</div>

app/views/courses/edit.html.erb
<%= link_to t('shared.all.crs_back'), courses_path(department_id: @department.id) %>
<div class ="course edit">
  <h2><%= t('courses.all.crs_update') %></h2>
  <%= simple_form_for @course, url: course_path(@course,department_id: @department.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :department_id, department_id: @department.id  %>
      <%= f.input :position %>
      <%= f.input :course_ID %>
      <%= f.input :course_name %>
      <%= f.input :credits %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="school index">
  <%= link_to t('shared.all.dept_back'), departments_path(school_id: @department.school_id) %>
  <div id= "showname">
    <p class="center"><%= t('departments.all.dept_of')%><%= @department.name %></p>
  </div>
  </table>
  <h2><%=t('courses.all.crs')%></h2>
  <%= image_tag('plus.png', size: '12x12', alt: '+') %>
  <%= link_to t('courses.all.crs_add'), new_course_path(department_id: @department.id) %>
  <br /><br />
  <table class="listing" summary="Course List">
    <tr class="header">
      <th><%=t('shared.all.serial')%></th>
      <th class="center"><%=t('courses.all.crs_ID')%></th>
      <th class="center"><%=t('courses.all.crs_name')%></th>
      <th class="center"><%=t('courses.all.crs_credit')%></th>
      <th class="center"><%=t('courses.all.crs_enroll')%></th>
      <th class="center"><%=t('shared.all.actions')%></th>
    </tr>
    <% @courses.each do |course| %>
        <tr>
          <td><%= course.position %></td>
          <td><%= course.course_ID %></td>
          <td><%= course.course_name %></td>
          <td><%= course.credits %></td>
          <td><%= course.students.size %></td>
          <td class="actions">
            <%= link_to t('courses.all.crs_std'), course_enrollments_path(course_id: course.id) %>
            <%= link_to t('shared.all.show'), course_path(course, department_id: @department.id) %>
            <%= link_to t('shared.all.edit'), edit_course_path(course, department_id: @department.id) %>
            <%= link_to t('shared.all.delete'), delete_course_path(course, department_id: @department.id) %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/courses/new.html.erb
<%= link_to t('shared.all.crs_back'), courses_path(department_id: @department.id) %>
<div class ="courses new">
  <h2><%= t('courses.all.crs_new') %></h2>
  <%= simple_form_for @course, url: courses_path(department_id: @department.id) do |f| %>
      <%= f.error_notification %>
      <%= f.hidden_field :department_id, department_id: @department.id  %>
      <%= f.input :position %>
      <%= f.input :course_ID %>
      <%= f.input :course_name %>
      <%= f.input :credits %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/courses/show.html.erb
<%= link_to t('shared.all.crs_back'), courses_path(department_id: @department.id) %>
<div class="schools show">
  <h2><%= t('courses.all.crs_details') %></h2>
  <table summary="Course detail view">
    <tr>
      <th><%= t('courses.all.crs_ID') %></th>
      <td><%= @course.course_ID %></td>
    </tr>
    <tr>
      <th><%= t('courses.all.crs_name') %></th>
      <td><%= @course.course_name %></td>
    </tr>
    <tr>
      <th><%= t('courses.all.crs_credit') %></th>
      <td><%= @course.credits %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.createdat') %></th>
      <td><%= @course.created_at %></td>
    </tr>
    <tr>
      <th><%= t('shared.all.updatedat') %></th>
      <td><%= @course.updated_at %></td>
    </tr>
  </table>
</div>